### ISSUE TITLE
Docker Version Variable Confusion (docker_latest_version & docker_version)

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#106]
What's the intended relationship between `docker_latest_version` and `docker_version`?

Is one supposed to trump the other?

[Version variables](https://github.com/haxorof/ansible-role-docker-ce/blob/f0a45b0db41256bef05f1487a7b5a2a37d6afe65/defaults/main.yml#L9-L16):
```
# Always ensure latest version of Docker CE
docker_latest_version: true
...
# Docker version
# ex. 18.06.1.ce-3.el7
docker_version: ''
```

**Comment by haxorof** [comment]
@jamiejackson I can confess that it became not that self explanatory. 😄 The relation between these variables are as follows:
* If `docker_version` is set to a non-empty value (e.g. `18.06.1.ce-3.el7`) then that is used.
* If `docker_version` is empty (default) and `docker_latest_version` is set to `true` (default) then latest version will be installed
* If `docker_version` is empty (default) and `docker_latest_version` is set to `false` then it will only install if its not already present

Maybe I should write this in some documentation somewhere. 😄 

Do ask me more questions if it is not clear!

**Comment by jamiejackson** [comment]
That's helpful, thanks.

As I mentioned in #105, I had been running my local environment without any docker versioning information, so the role had installed v19. Now that I want to downgrade, I'm running into trouble

```yaml
docker_swarm:
  advertise_nic: ens192
docker_compose_ver: 1.23.2
docker_enable_audit: true
docker_enable_ce_edge: false
docker_enable_mount_flag_fix: false
docker_enable_swarm: true
docker_daemon_config:
  # bip gets docker0 to have a consistent ip. need that to access host's
  # postfix from the container: 
  # https://jira.icfwebservices.com/browse/CPD-10025?focusedCommentId=394243
  bip: 172.17.0.1/16
  disable-legacy-registry: true
  debug: false
  icc: false
  init: true
  live-restore: false
  log-driver: journald
  storage-driver: overlay2
  userland-proxy: false
# to figure out available versions: `yum --showduplicates list docker-ce``
docker_version: '3:19.03.0-3.el7'
```
Available versions: https://gist.github.com/jamiejackson/07b5bd0a948cc8a0ecb18bb8fa9047ea

I keep seeming to end up with v19 even if I `sudo yum remove docker-ce`, then re-run the role:

```
$ docker --version
Docker version 19.03.0, build aeac9490dc
```
