### ISSUE TITLE
Kernel parameter fs.may_detach_mounts is necessary even if mount flag is set to slave

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#13]
I just discovered this role today. It covers a lot of bases, but it might be missing one.

I had been having issues on my host (with another Docker role, FWIW) until I added the following:

```yml
    - name: 'may_detach_mounts workaround (https://github.com/moby/moby/pull/34886 & https://github.com/moby/moby/issues/34538#issuecomment-331533940)'
      become: yes
      copy:
        content: |
          fs.may_detach_mounts=1
        dest: /etc/sysctl.d/may_detach_mounts.conf
      register: may_detach_mounts_config
    
    - name: activate may_detach_mounts
      command: sysctl -p  /etc/sysctl.d/may_detach_mounts.conf
      become: yes
      when: may_detach_mounts_config.changed
```

I see this (https://github.com/haxorof/ansible-role-docker-ce/blob/master/tasks/main-Mountflags.yml) but IIRC, I'd encountered an issue even with that set.

Thoughts?

## References:

* https://github.com/moby/moby/issues/34538#issuecomment-331533940
* https://github.com/moby/moby/pull/34886
