### ISSUE TITLE
Docker-compose download checksum verification fails.

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#154]
### Version Information

Ansible: `2.9.27`

Role: `3.7.2`

### Steps to Reproduce
Install latest precompiled docker-compose(2.10.0).

### Expected Behavior
Download precompiled file and verify checksum.

### Actual Behavior
Download of docker-compose works however the sha sum file is now only in the common file no separate files so this fails.
checksums.txt

### References
https://github.com/docker/compose/releases/tag/v2.10.0

**Comment by janorn** [comment]
https://github.com/haxorof/ansible-role-docker-ce/blob/1b4feedb1437467ba54b496d38960ddbef362215/tasks/postinstall.yml#L272-281

**Comment by janorn** [comment]
https://github.com/haxorof/ansible-role-docker-ce/blob/1b4feedb1437467ba54b496d38960ddbef362215/tasks/postinstall.yml#L272-L281

**Comment by janorn** [comment]
This works from 2.10.0 unfortunatly not for 2.9.0.

```yaml
---
- name: Test
  hosts: localhost
  connection: local
  tasks:
    - name: Download file with checksum url (sha256)
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64
        dest: /tmp/docker-compose
        checksum: sha256:https://github.com/docker/compose/releases/download/v2.10.0/checksums.txt
```
