### ISSUE TITLE
Task "Configure Docker daemon" fails because of missing directory

### ISSUE THREAD

**Issue by haxorof** [haxorof/ansible-role-docker-ce#2]
Executing the role with defined Docker daemon configuration fail in clean environment:
```yaml
---
- hosts: localhost
  roles:
    - role: haxorof.docker-ce
      docker_daemon_config:
          init: true
```

Failing task:
```
TASK [haxorof.docker-ce : Configure Docker daemon] *********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "c1a367475776e627b21c8d85b9be8e74af93995c", "failed": true, "msg": "Destination directory /etc/docker does not exist"}
```
