### ISSUE TITLE
Optional dm.directlvm_device

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#25]
This is really an Ansible question, but I'm having trouble getting help with it.

Some of my hosts will have a different device for `dm.directlvm_device`--not a problem, I can use a variable for that. However, some hosts don't have a dedicated `dm.directlvm_device`. I'm not sure how to toggle the presence of the `dm.directlvm_device` element (or alternatively, I guess, the `storage-opts` key).

Do you have any suggestions?

```yaml
- hosts: dockerhosts
  vars:
    docker_compose_version: 1.16.1
    docker_enable_audit: true
    docker_enable_ce_edge: true
    docker_daemon_config:
      icc: false
      init: true
      disable-legacy-registry: true
      live-restore: true
      userland-proxy: false
      log-driver: journald
      storage-driver: devicemapper
      storage-opts:
        - "dm.directlvm_device=/dev/sdb2"
      # remove for real servers?
      debug: true
    force_secrets_recreation: false
    do_decryption_test: false
    do_dump: false
    myname: "{{myuser | default('hosting') }}"
    media_share_ignore_mount_errors: false
    ignore_user_creation_errors: false
  roles:
    - role: haxorof.docker-ce
      tags: [docker]
    - role: franklinkim.docker-compose
      tags: [docker-compose]
      become: yes
```

**Comment by jamiejackson** [comment]
It was easier than I thought:

playbook.yml
```yaml
- hosts: dockerhosts
  vars:
    ...
    docker_daemon_config:
      ...
      storage-opts: "{{ docker_daemon_config_storage_opts }}"
     ...
```

Some hosts have no storage opts:

```yaml
docker_daemon_config_storage_opts: 
```

And some will:

```yaml
docker_daemon_config_storage_opts:
  - "dm.directlvm_device=/dev/sdb2"
```
