### ISSUE TITLE
Namespace problem in CentOS 7.4

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#32]
OS: `CentOS Linux release 7.4.1708 (Core)`

My ultimate target is RHEL 7.4, but I'm working on CentOS, ATM.

Have you used namespaces yet? I'm having issues.

I'm going to paste in my notes from my own private issue tracker:

Details: https://docs.docker.com/engine/security/userns-remap/#enable-userns-remap-on-the-daemon

Notes:

In trying to implement this, I added the following to the playbook, however docker wouldn't restart.
```yml
  vars:
    ...
    docker_daemon_config:
      ...
      userns-remap: default
    ...
```

`/var/log/messages` told me that docker was having a problem using the extant files/filesystem, so I did a `vagrant destroy slave`.

Once I ran `vagrant up` from scratch, docker started, but I go this:
```sh
$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Pull complete
Digest: sha256:97ce6fa4b6cdc0790cda65fe7290b74cfebd9fa0c9b8c38e979330d547d22ce1
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 40\"": unknown.
ERRO[0002] error waiting for container: context canceled
```

That led me to these references:

* https://github.com/opencontainers/runc/issues/1513#issuecomment-372633145
* https://github.com/procszoo/procszoo/wiki/How-to-enable-%22user%22-namespace-in-RHEL7-and-CentOS7%3F

I then ran the following and rebooted the VM:

```sh
$ sudo grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
$ sudo grubby --args="namespace.unpriv_enable=1" --update-kernel="$(grubby --default-kernel)"
```

Upon restart:

```sh
$ docker run --rm hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
ca4f61b1923c: Pull complete
Digest: sha256:97ce6fa4b6cdc0790cda65fe7290b74cfebd9fa0c9b8c38e979330d547d22ce1
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
```

Todo:

* Figure out the bare minimum of configs to get this stuff working (are both boot args needed or just one?)
* Figure out how to set whatever's needed in Ansible
  * If a role is used, [this](https://galaxy.ansible.com/jtyr/grub_cmdline/) seems to be the only one that both
    * Runs on RHEL (and CentOS?)
    * Supports arbitrary arguments

**Comment by haxorof** [comment]
Yes, I have tried this before and worked for me. I see that you enabled user namespaces using grubby but it might be that you are only missing one little thing more. Have a look at the link below and you see you might need to increase user.max_user_namespaces so it is higher than zero: https://success.docker.com/article/user-namespace-runtime-error

If that does not resolve you issue I can have a go at it here and see on a CentOS 7.4.

Cheers!

**Comment by jamiejackson** [comment]
> Yes, I have tried this before and worked for me.

Did you have to do extra tweaks outside of the role to make it work? Had you tried it on a version of CentOS that had the issue?

I'm thinking ahead to getting the role to correctly configure namespace support, and whether the hacks in the [article that you mentioned](https://success.docker.com/article/user-namespace-runtime-error) could be applied across the board or whether they'd need to be based on whether `userns-remap` is set (and/or whichever other parameters).

By the way, I'm completely new to the namespace thing, but I used `userns-remap: default`, which resulted in both `/etc/subgid` and `/etc/subuid` getting set to `dockremap:500000:65536`, so I don't _think_ the extra steps of populating these files are necessary.

**Comment by haxorof** [comment]
The kernel changes etc I do outside in for example a different role which is responsible for more kernel or similar. Not sure if I tried it on CentOS 7.4.

Do not want this Docker role to do too much tweaks on the OS because it then it might do to much and other roles might then have conflicting configs. Related to user namespaces this role assumes the OS is configured correctly before this role applies config which uses the user namespaces feature.

Reason for the role handling the subgid and subuid in default scenario is because Docker did not do that correctly across distributions so the Docker daemon did not start out-of-the-box.

**Comment by jamiejackson** [comment]
This is what I've got so far, which seems to work. After a reboot, it seems to work (i.e., `docker run --rm hello-world` runs properly).



```yml
# https://success.docker.com/article/user-namespace-runtime-error

- hosts: dockerhosts
  tags:
    - namespaces
    - docker
  roles:
    - role: jtyr.grub_cmdline
      vars:
        grub_cmdline_add_args:
          - namespace.unpriv_enable=1
          - user_namespace.enable=1
      become: yes
  tasks: 

  - name: set user.max_user_namespaces
    sysctl: 
      name: user.max_user_namespaces
      value: 15000
      sysctl_set: yes
      state: present
      reload: yes
    become: yes
  
- hosts: dockerhosts
  vars:
    ...
    docker_daemon_config:
      ...
      userns-remap: default
    ...
  roles:
    - role: haxorof.docker-ce
      tags: [docker]
```
