### ISSUE TITLE
Docker Daemon Config Change doesn't Trigger Restart

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#38]
I made a change (`docker_daemon_config.live-restore: true` => `false`), and the change wasn't manifest until I restarted the daemon manually.

Changes to `daemon.json` should trigger a daemon restart.

**Comment by haxorof** [comment]
Hi @jamiejackson !

I just did a test in a CentOS 7 and the trigger to restart the Docker is happening every time I do a change in `docker_daemon_config`. Here is the playbook I used in the test:
```yaml
---
- hosts: localhost
  vars:
    docker_enable_mount_flag_fix: no
    docker_daemon_config:
      live-restore: true
  roles:
    - haxorof.docker-ce
```

Below is the Ansible version I used:
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

What version of Ansible do you use?

Cheers!
