### ISSUE TITLE
Cannot set hosts in daemon.json because of arguments to dockerd

### ISSUE THREAD

**Issue by haxorof** [haxorof/ansible-role-docker-ce#42]
It is not possible to only use `docker_daemon_config` to configure Docker daemon to for example also expose the TCP socket, see example below:
```yaml
---
- hosts: localhost
  roles:
    - role: haxorof.docker-ce
      docker_daemon_config:
        hosts:
          - "tcp://0.0.0.0:2376"
          - "fd://"
        tlsverify: true
        tlscacert: "/etc/docker/ssl/ca.pem"
        tlscert: "/etc/docker/ssl/cert.pem"
        tlskey: "/etc/docker/ssl/key.pem"
```

You will see this error in the journal logs:
```
Jun 23 19:46:42 labrat dockerd[32221]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [tcp://0.0.0.0:2376 fd://])
```
