### ISSUE TITLE
Devicemapper setup

### ISSUE THREAD

**Issue by britishbadger** [haxorof/ansible-role-docker-ce#7]
Hi
I was trying to setup devicemapper using the 
    docker_setup_devicemapper: true

Unfotunately this seems to skip on the following check
  when: docker_stat_storage.stat.exists == false
in main-Storage and I couldn't work out where this is set.

I found the project atomic storage setup instructions http://www.projectatomic.io/docs/docker-storage-recommendation. 

Using this setup should I need to do anything further like add DEVS to option to /etc/sysconfig/docker-storage-setup as part of the ansible setup.
e.g.
`DEVS="/dev/vdb"
`

I believe the devicemapper storage can now be setup by docker from 17.06 (https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production). This works correctly If I set the following but it still doesn't seem to use the setup storage scripts.

```
vars 
    docker_enable_audit: true
    docker_setup_devicemapper: true
docker_daemon_config:
        icc: false
        init: true
        userns-remap: default
        disable-legacy-registry: true
        live-restore: true
        userland-proxy: false
        log-driver: journald
        storage-driver: devicemapper
        storage-opts:
          - "dm.directlvm_device=/dev/sdb"
          - "dm.thinp_percent=95"
          - "dm.thinp_metapercent=1"
          - "dm.thinp_autoextend_threshold=80"
          - "dm.thinp_autoextend_percent=20"
          - "dm.directlvm_device_force=false"
```
Just wondering if it all works for you on a clean setup

**Comment by haxorof** [comment]
Hi @britishbadger 

First of all I would just say that this implementation to setup the device mapper is quite simple at the time. When I tried to follow the Docker instructions to setup the device mapper it initially did not work well on Fedora I think. So I went for utilizing project atomic's setup scripts.

This docker_stat_storage is basically used to avoid doing the storage setup steps if file `/usr/lib/systemd/system/docker-storage-setup.service` already exists. This assumes that the docker storage has already been setup and this role will just use it.

I have not done any extensive testing on this my self but tried on a CentOS 7.2. On CentOS I did a clean setup but not yet on Fedora. 

@britishbadger: What distribution do you use CentOS or Fedora?

How I tested this was to create simple playbook which you can find [here](ansible-role-docker-ce/blob/master/tests/test_config_storage.yml). What happens is that these storage options will be written to the file `/etc/sysconfig/docker-storage` so I do not specify anything around storage-opts in the daemon config. Then this role setup a [docker.service drop-in file](ansible-role-docker-ce/files/etc/systemd/system/docker.service.d/docker-storage.conf) which will ensure these options will be available for the Docker engine. So nothing more advance than this I have tried right now.

So in your case your playbook shall not include the storage stuff because that shall be already present in the docker-storage file. It can possibly be that the simple setup I have done of the storage is not enough for your usage so then I will have to revise what can be done. Anyway I would assume your playbook would look something like this:
```yaml
vars 
    docker_enable_audit: true
    docker_setup_devicemapper: true
    docker_daemon_config:
        icc: false
        init: true
        userns-remap: default
        disable-legacy-registry: true
        live-restore: true
        userland-proxy: false
        log-driver: journald
```

I will see if I can do some more testing on this and look at the Docker documentation again too see if it is possible to just follow that. I believe however that in the Docker documentation that you have already setup the logical thin volumes etc which is actually done by the project atomic scripts. Anyway, I will check what has been updated etc.

Cheers!

**Comment by britishbadger** [comment]
I've ran this on Centos 7.3.  Looking through the files, /etc/sysconfig/docker-storage never gets created. I'll create a new VM and try again and let you know. 

Thanks

**Comment by haxorof** [comment]
Thanks!
The docker-storage shall be created if the service `docker-storage-setup` starts correctly. Check `systemctl status docker-storage-setup` to see if it complains or not.

Let me know if you find something after you tested again in a new VM.

Cheers!

**Comment by britishbadger** [comment]
I definately remember that failing, but I guess because /usr/lib/systemd/system/docker-storage-setup.service is then set, means things are skipt ? I'm just re-provisioning my vm so will know shortly

**Comment by haxorof** [comment]
Thanks for letting me know about this.

Yes, I will have to do some improvements there (will write issue on this). I just tried it now and failed the first time and then the role will just skip the steps even if the storage setup failed.

**Comment by haxorof** [comment]
Hmm.. now when I tried the docker-storage-setup it now failed as seen below when I had added a physical volume (/dev/sdb) to a volume group:
```
[root@localhost ~]# systemctl status docker-storage-setup.service
● docker-storage-setup.service - Docker Storage Setup
   Loaded: loaded (/usr/lib/systemd/system/docker-storage-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-07-21 14:37:06 UTC; 7s ago
  Process: 23985 ExecStart=/usr/bin/container-storage-setup (code=exited, status=5)
 Main PID: 23985 (code=exited, status=5)

Jul 21 14:37:05 localhost.localdomain systemd[1]: Starting Docker Storage Setup...
Jul 21 14:37:06 localhost.localdomain container-storage-setup[23985]: Using default stripesize 64.00 KiB.
Jul 21 14:37:06 localhost.localdomain container-storage-setup[23985]: Rounding up size to full physical extent 88.00 MiB
Jul 21 14:37:06 localhost.localdomain container-storage-setup[23985]: Insufficient suitable allocatable extents found for logical volume docker-pool.
Jul 21 14:37:06 localhost.localdomain systemd[1]: docker-storage-setup.service: main process exited, code=exited, status=5/NOTINSTALLED
Jul 21 14:37:06 localhost.localdomain systemd[1]: Failed to start Docker Storage Setup.
Jul 21 14:37:06 localhost.localdomain systemd[1]: Unit docker-storage-setup.service entered failed state.
Jul 21 14:37:06 localhost.localdomain systemd[1]: docker-storage-setup.service failed.
```

I have not see this before and it seem the lvcreate command failed for me. To fix this I needed to execute the lvcreate command which was executed in `/usr/bin/container-storage-setup` . Running to get the lvcreate command I needed I first executed the script as root like this: `bash -x /usr/bin/container-storage-setup`

The last line which was executed in the bash script looked like this for me:
```
+ lvcreate -y --type thin-pool --zero n -c 512K --poolmetadatasize 176145s -l 40%FREE -n docker-pool cl
```

So I added /dev/sdb1 to the end and that solved it for me:
```
lvcreate -y --type thin-pool --zero n -c 512K --poolmetadatasize 176145s -l 40%FREE -n docker-pool cl /dev/sdb1
```

Googling around a bit and I saw this quite fresh bug report which might have something to do with it but need to investigate further: https://bugzilla.redhat.com/show_bug.cgi?id=1416885

I have not tried the device mapper now where `vgs` show me I got more the 2G free when only having one disk.

**Comment by haxorof** [comment]
@britishbadger As you said Docker has done some improvements related to setting up the devicemapper in v17.06 and now I tried a minimal config to get that up and running which works in my CentOS 7.3.1611:
```yaml
---
- hosts: test-host
  vars:
    docker_daemon_config:
      icc: false
      init: true
      #userns-remap: default
      disable-legacy-registry: true
      live-restore: true
      userland-proxy: false
      log-driver: journald
      storage-driver: devicemapper
      storage-opts:
        - "dm.directlvm_device=/dev/sdb1"      
  roles:
    - haxorof.docker-ce
```
**Note!** I cannot set `userns-remap` to default because it seems Docker daemon tries to create dockremap user and uses a command which does is not compatible with CentOS.

After Docker daemon is started it looks like this when executing `lsblk`
```
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                         8:0    0   80G  0 disk
├─sda1                      8:1    0    1G  0 part /boot
└─sda2                      8:2    0   79G  0 part
  ├─cl-root               253:0    0   50G  0 lvm  /
  ├─cl-swap               253:1    0    1G  0 lvm  [SWAP]
  └─cl-home               253:2    0   28G  0 lvm  /home
sdb                         8:16   0    5G  0 disk
└─sdb1                      8:17   0  3.1G  0 part
  ├─docker-thinpool_tmeta 253:3    0   28M  0 lvm
  │ └─docker-thinpool     253:5    0    3G  0 lvm
  └─docker-thinpool_tdata 253:4    0    3G  0 lvm
    └─docker-thinpool     253:5    0    3G  0 lvm
```
