### ISSUE TITLE
api.github.com limits on number of requests causes the request to fail

### ISSUE THREAD

**Issue by haxorof** [haxorof/ansible-role-docker-ce#87]
Currently installation of docker-compose in this role uses the api.github.com to determine latest version. This API is limited to number of requests so in bigger environments that uses this the request limit might be reached and causes the request to fail.

### Ansible Version

```
2.7.8
```

### Role Version

```
2.2.0
```

### Role configuration

```yaml
docker_compose: true
docker_compose_no_pip: true
...
```

### Expected Behavior

Docker compose successfully downloaded and installed.

### Actual Behavior

Task `Get latest release of docker-compose` failed

### Steps to Reproduce

```yaml
---
- name: Test install of Docker compose not using PiP
  hosts: test-host
  vars:
    docker_compose: true
    docker_compose_no_pip: true
  roles:
    - haxorof.docker-ce
...
```

**Comment by haxorof** [comment]
Added new configuration options to fix this:
```yaml
# Uses Github API to lookup latest version of docker compose
docker_compose_no_pip_detect_version: true
# Docker compose version to use if no automatic lookup is used
docker_compose_no_pip_version: 1.24.0
```
