### ISSUE TITLE
RHEL: subscription-manager uses network when docker_network_access is set to false

### ISSUE THREAD

**Issue by haxorof** [haxorof/ansible-role-docker-ce#98]
### Ansible Version

```
2.6.16
```

### Role Version

```
2.4.0
```

### Role configuration

```yaml
- name: Install and configure Docker CE
  hosts: test-host
  roles:
    - haxorof.docker_ce

- name: No outbound network shall be required to reconfigure Docker CE
  hosts: test-host
  vars:
    docker_network_access: false
    docker_daemon_config:
      icc: false    
  roles:
    - haxorof.docker_ce
```

### Expected Behavior

Outbound network connectivity shall not be necessary when run the second time on RHEL.

### Actual Behavior

subscription-manager was called which requires network connectivity and the role failed the second time.

### Steps to Reproduce

See config above but for second run outbound network connectivity must be blocked.

### References

None
